### ISSUE TITLE
regarding evaluation of the trained model

### ISSUE THREAD

**Issue by ctsrkrk** [Hzzone/MTLFace#1]
Hi, 
Just wanted to ask that could you provide the code to run, test and evaluate the trained model and get the age progressions.
The code to train the model is present but where can I find the code to test it?

Thanks

**Comment by Hzzone** [comment]
I am sorry for that now I have no time to rewrite the code you have requested... You could get the images from the following code, it is very simple to adjust for your own need https://github.com/Hzzone/MTLFace/blob/4ed43c77a5b671fb609f3e010845a2a423be3865/models/fas.py#L75

I am preparing for my journal version, and maybe I would public them together in the future.
