### ISSUE TITLE
SCAF dataset

### ISSUE THREAD

**Issue by liliiscaiji** [Hzzone/MTLFace#12]
May I ask whether the SCAF data set mentioned in your paper for fair comparison has been published?

**Comment by baiyun442** [comment]
> The dataset is available at https://www.dropbox.com/s/o7zbnzlkpwczbg2/small.txt?dl=0; see https://hzzone.github.io/MTLFace/
The link is invalid, can you share it again

**Comment by baiyun442** [comment]
> May I ask whether the SCAF data set mentioned in your paper for fair comparison has been published?

Have you obtained the SCAF dataset? Can you share it? The official link has expired
