### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by liliiscaiji** [Hzzone/MTLFace#14]
![image](https://user-images.githubusercontent.com/105691533/204813303-e237b809-6756-4916-8be3-99c5503bd6d6.png)
Hello! I want to try the demo in your web page https://hzzone.github.io/MTLFace/, but an error, could you tell me what causes, how to solve?

**Comment by Hzzone** [comment]
Thanks for your feedback. The cpp extensions have not been installed in jupyter notebook. I have updated the notebook to match Colab.
