### ISSUE TITLE
Questions to Ask

### ISSUE THREAD

**Issue by liliiscaiji** [Hzzone/MTLFace#15]
Thank you for your answer, but there was another problem when I tried today. I thought about it for a long time but did not solve it. I come to ask you again, hoping to get your reply!
![image](https://user-images.githubusercontent.com/105691533/204960153-e6f75ea0-f7f6-4c71-b093-e2bc2e219da6.png)

**Comment by Hzzone** [comment]
If you are running on the local machine, you should make sure to upgrade your nvcc.
try `nvcc -V` to see which version you use, and add the latest CUDA~(maybe CUDA10+) to your environment `export PATH=/usr/local/cuda/bin:$PATH`.
