### ISSUE TITLE
Can't find the evaluation protocol 

### ISSUE THREAD

**Issue by tom99763** [Hzzone/MTLFace#16]
Your code does not have any evaluation protocol. How do you evaluate your model to get the results in the paper.

**Comment by SpLakeb** [comment]
i found this problem too

**Comment by Hzzone** [comment]
Following standard LFW evaluation protocols. You can refer to https://www.dropbox.com/scl/fi/divn9pmzzeuo8llbz8i9x/evaluation.py?rlkey=f586jxhde6zm51q01oqwhetik&st=1f1g4sdy&dl=0
