### ISSUE TITLE
RuntimeError: Error building extension 'fused'

### ISSUE THREAD

**Issue by 20193939** [Hzzone/MTLFace#17]
May I ask, I rewrote your example.ipynb into .py file for execution in windows, but there will be an error, can you tell me the reason?
![0`1 Q5CQLIL` $(M1M(QY 0](https://user-images.githubusercontent.com/59442564/213914767-85dab084-3097-4591-aeeb-3918b46f56c7.png)
![)U{()Q`BY 33IQR8O A1IDN](https://user-images.githubusercontent.com/59442564/213914773-87651755-b31c-41df-a9e9-c0f1b2f32293.png)

**Comment by Hzzone** [comment]
Hi, you may need `pip install ninja`.
