### ISSUE TITLE
File not found error!!

### ISSUE THREAD

**Issue by Watebear** [Hzzone/MTLFace#2]
Hello, thanks for sharing your code.
I am very interesting in your work.
I run your code but meet this error:

FileNotFoundError: File b'/data/xxx/Face/MTLFace/dataset/scaf.txt' does not exist

The file is not in your baidu netdisk.

**Comment by yiyifengping** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/xxx/xxx/xxx/MTLFace/dataset/None.txt'

**Comment by quleileileilei** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxx/xxx/MTLFace-master/dataset/ms1m/16490/1294129.jpg'

**Comment by zhangbaijin** [comment]
> 

Have you solved the problem? How to solve it

**Comment by wangmengmeng99** [comment]
这样配置parser.add_argument("--dataset_name", "-d", default='casia-webface',help='input image size', type=str)
![1715334355012](https://github.com/Hzzone/MTLFace/assets/29188125/9209a5ea-f159-474d-9196-4b0c4aa2127e)
