### ISSUE TITLE
Cannot save models/images

### ISSUE THREAD

**Issue by holy33669** [Hzzone/MTLFace#4]
Thanks for your great job!

After train AIFR/FAS, there is no file in output.
Is there a solution?Thank you!

**Comment by Hzzone** [comment]
Thanks for your interest. This code has not saved the output images, I plan to upload the refactored code in soon ~2 weeks. If urgent, you can reference https://github.com/Hzzone/MTLFace/blob/4ed43c77a5b671fb609f3e010845a2a423be3865/models/fas.py#L81
I will let you know once there is any update.

**Comment by holy33669** [comment]
> Thanks for your interest. This code has not saved the output images, I plan to upload the refactored code in soon ~2 weeks. If urgent, you can reference
> 
> https://github.com/Hzzone/MTLFace/blob/4ed43c77a5b671fb609f3e010845a2a423be3865/models/fas.py#L81
> 
> 
> I will let you know once there is any update.

Thank you for your reply!

**Comment by sleepy678** [comment]
my coding ability is so bad that I can't finish the validating...waiting for the updating.Thank you.

**Comment by quleileileilei** [comment]
May I ask when you can update it and upload it？
