### ISSUE TITLE
Evaluation on AIFR

### ISSUE THREAD

**Issue by XinruiYuan** [Hzzone/MTLFace#5]
Thank you for your contribution.

I have a question about the evaluation on AIFR. You used a id-classification task fulfilling id-label prediction and calculating CE loss between id-pred-classification and id-gt on SCAF, while evaluated on AgeDB.  

I was wondering how can you evaluate on AgeDB30 since the id-gts are not given and obviously differ from SCAF, then how can you calculate the verification accuracy? Did you also train a verification module or just calculate similarity between "embedding" obtained by backbone of two inputs given by AgeDB30?

Looking forward to your reply.

Thanks

**Comment by Hzzone** [comment]
Using the embedding following the traditional face recognition.
