### ISSUE TITLE
Plot generated image from generator - FAS

### ISSUE THREAD

**Issue by ngthalogit** [Hzzone/MTLFace#8]
Thanks for your great job!

After train FAS, I try to plot the image generated from generator, but it's not work. Can you tell how to plot it correctly? Thanks

**Comment by Hzzone** [comment]
```python
from torchvision.transforms.functional import to_pil_image
from torchvision.utils import make_grid
to_pil_image(make_grid(g_source))
```

**Comment by ngthalogit** [comment]
Thanks your response! 
I followed your instruction but it still doesn't work. This is my result:
<img width="818" alt="Screen Shot 2022-06-29 at 9 28 56 AM" src="https://user-images.githubusercontent.com/83007241/176338197-0ab0825f-dd57-447d-a476-0a775d9cd7ea.png">

**Comment by ngthalogit** [comment]
> ```python
> from torchvision.transforms.functional import to_pil_image
> from torchvision.utils import make_grid
> to_pil_image(make_grid(g_source))
> ```

Thanks for your response! 
I followed your instruction but it still doesn't work. This is my result:
<img width="818" alt="Screen Shot 2022-06-29 at 9 28 56 AM" src="https://user-images.githubusercontent.com/83007241/176338197-0ab0825f-dd57-447d-a476-0a775d9cd7ea.png">
I try to make the result like this, can you give me the instruction ? Thanks 
<img width="708" alt="Screen Shot 2022-06-29 at 9 33 47 AM" src="https://user-images.githubusercontent.com/83007241/176338743-59dca203-9546-49f1-919b-5e7c9eeba028.png">
