### ISSUE TITLE
FAS visualization

### ISSUE THREAD

**Issue by ngthalogit** [Hzzone/MTLFace#9]
Thanks for your great job! 
I have tried to plot output of generator using torchvision.utils.make_grid but it still didn't work. This is my result: 
<img width="818" alt="Screen Shot 2022-06-29 at 9 28 56 AM" src="https://user-images.githubusercontent.com/83007241/176338197-0ab0825f-dd57-447d-a476-0a775d9cd7ea.png">
I am trying to make the result like this below image, can you give me the instruction ? Thanks !
<img width="708" alt="Screen Shot 2022-06-29 at 9 33 47 AM" src="https://user-images.githubusercontent.com/83007241/176338743-59dca203-9546-49f1-919b-5e7c9eeba028.png">

**Comment by Hzzone** [comment]
It seems that you have not trained the FAS well, which caused the results like random images.

**Comment by ngthalogit** [comment]
> It seems that you have not trained the FAS well, which caused the results like random images.

Hmm, can you send me the generator's weight file ? I really need to plot the result of FAS, pls help me ! thanks
